[project]
name = "hhscribe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx",
    "pandas",
    "pydantic",
    "python-dotenv",
    "beautifulsoup4",
    "lxml"
]
